#!/bin/bash

set -eu

cd $(dirname $0)

INPUT_FILE_NAME="INPUT"
APP_SOURCE_NAME="App.java"
PREDEF_SOURCE_NAME="Predef.java"
APP_CLASS_NAME="com.mayreh.sus4.App"

usage() {
    echo "Usage: ./sus4 (exec|save) [category] [title]"
    exit 1
}

exec_java() {
    javac -d out -classpath . $PREDEF_SOURCE_NAME $APP_SOURCE_NAME
    cat $INPUT_FILE_NAME | java -classpath out $APP_CLASS_NAME
}

save() {
    category=$1
    title=$2
    filename="$category/$title/$APP_SOURCE_NAME"
    mkdir -p "$category/$title"
    timestamp=$(date "+%Y%m%d%H%M%S")

    cp -r $APP_SOURCE_NAME "$category/$title/${timestamp}_$APP_SOURCE_NAME"
}

if [ "$#" -lt 1 ]; then
    usage
fi

command="$1"

case $command in
    "exec" )
        exec_java
        ;;
    "save" )
        if [ "$#" -ne 3 ]; then
            usage
        fi

        save $2 $3
        ;;
    * )
        usage
        ;;
esac
